version: '3.8'

services:
  uz-bot:
    build: .
    container_name: uz-ticket-watcher
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
